<?php

const INTEGRACAO_SALVAR_DADOS = 'INTEGRACAO_SALVAR_DADOS';
const INTEGRACAO_REGISTRAR_PAGAMENTO = 'INTEGRACAO_REGISTRAR_PAGAMENTO';
const INTEGRACAO_EMPRESA_ATUALIZAR_DADOS = 'INTEGRACAO_EMPRESA_ATUALIZAR_DADOS';
const INTEGRACAO_EMPRESA_ATUALIZAR_DADOS_FALHA = 'INTEGRACAO_EMPRESA_ATUALIZAR_DADOS_FALHA';
const INTEGRACAO = 'INTEGRACAO.*';

const ALL_TOPICS = [
    INTEGRACAO_SALVAR_DADOS,
    INTEGRACAO_REGISTRAR_PAGAMENTO,
    INTEGRACAO_EMPRESA_ATUALIZAR_DADOS,
    INTEGRACAO_EMPRESA_ATUALIZAR_DADOS_FALHA,
];
